version: 2.1


common: &common
  working_directory: ~/project
  steps:
    - checkout
    - restore_cache:
        keys:
          - v2-deps-{{ .Environment.CIRCLE_JOB }}-{{ checksum "tox.ini" }}
    - run:
        name: install dependencies
        command: pip install --user tox
    - run:
        name: run tox
        command: ~/.local/bin/tox -i $PIP_INDEX_URL
    - save_cache:
        paths:
          - .tox
          - ~/.cache/pip
          - ~/.local
          - ./eggs
        key: v2-deps-{{ .Environment.CIRCLE_JOB }}-{{ checksum "tox.ini" }}


jobs:
  py35:
    <<: *common
    docker:
      - image: circleci/python:3.5
        environment:
          TOXENV=py35-dj20-drf311,py35-dj21-drf311,py35-dj22-drf311
  py36:
    <<: *common
    docker:
      - image: circleci/python:3.6
        environment:
          TOXENV=py36-dj20-drf311,py36-dj21-drf311,py36-dj22-drf311
  py37:
    <<: *common
    docker:
      - image: circleci/python:3.7
        environment:
          TOXENV=py37-dj20-drf311,py37-dj21-drf311,py37-dj22-drf311
  py38:
    <<: *common
    docker:
      - image: circleci/python:3.8
        environment:
          TOXENV=py38-dj22-drf311,py38-dj30-drf311,py38-dj31-drf311

workflows:
  test:
    jobs:
      - py35
      - py36
      - py37
      - py38
